import { Inter } from "next/font/google";
import '../styles/globals.css';
import '../styles/fonts.css';   

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MangaQuizz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
